/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppVendorsRouteImport } from './routes/_app/vendors'
import { Route as AppStatementsRouteImport } from './routes/_app/statements'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppReportsRouteImport } from './routes/_app/reports'
import { Route as AppPaymentsRouteImport } from './routes/_app/payments'
import { Route as AppInventoryRouteImport } from './routes/_app/inventory'
import { Route as AppExpensesRouteImport } from './routes/_app/expenses'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppCustomersRouteImport } from './routes/_app/customers'
import { Route as AppCashflowRouteImport } from './routes/_app/cashflow'
import { Route as AppActivityRouteImport } from './routes/_app/activity'
import { Route as AppPurchasesIndexRouteImport } from './routes/_app/purchases.index'
import { Route as AppInvoicesIndexRouteImport } from './routes/_app/invoices.index'
import { Route as AppPurchasesNewRouteImport } from './routes/_app/purchases.new'
import { Route as AppInvoicesNewRouteImport } from './routes/_app/invoices.new'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppVendorsRoute = AppVendorsRouteImport.update({
  id: '/vendors',
  path: '/vendors',
  getParentRoute: () => AppRoute,
} as any)
const AppStatementsRoute = AppStatementsRouteImport.update({
  id: '/statements',
  path: '/statements',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppPaymentsRoute = AppPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AppRoute,
} as any)
const AppInventoryRoute = AppInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AppRoute,
} as any)
const AppExpensesRoute = AppExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCustomersRoute = AppCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AppRoute,
} as any)
const AppCashflowRoute = AppCashflowRouteImport.update({
  id: '/cashflow',
  path: '/cashflow',
  getParentRoute: () => AppRoute,
} as any)
const AppActivityRoute = AppActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AppRoute,
} as any)
const AppPurchasesIndexRoute = AppPurchasesIndexRouteImport.update({
  id: '/purchases/',
  path: '/purchases/',
  getParentRoute: () => AppRoute,
} as any)
const AppInvoicesIndexRoute = AppInvoicesIndexRouteImport.update({
  id: '/invoices/',
  path: '/invoices/',
  getParentRoute: () => AppRoute,
} as any)
const AppPurchasesNewRoute = AppPurchasesNewRouteImport.update({
  id: '/purchases/new',
  path: '/purchases/new',
  getParentRoute: () => AppRoute,
} as any)
const AppInvoicesNewRoute = AppInvoicesNewRouteImport.update({
  id: '/invoices/new',
  path: '/invoices/new',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/activity': typeof AppActivityRoute
  '/cashflow': typeof AppCashflowRoute
  '/customers': typeof AppCustomersRoute
  '/dashboard': typeof AppDashboardRoute
  '/expenses': typeof AppExpensesRoute
  '/inventory': typeof AppInventoryRoute
  '/payments': typeof AppPaymentsRoute
  '/reports': typeof AppReportsRoute
  '/settings': typeof AppSettingsRoute
  '/statements': typeof AppStatementsRoute
  '/vendors': typeof AppVendorsRoute
  '/invoices/new': typeof AppInvoicesNewRoute
  '/purchases/new': typeof AppPurchasesNewRoute
  '/invoices/': typeof AppInvoicesIndexRoute
  '/purchases/': typeof AppPurchasesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/activity': typeof AppActivityRoute
  '/cashflow': typeof AppCashflowRoute
  '/customers': typeof AppCustomersRoute
  '/dashboard': typeof AppDashboardRoute
  '/expenses': typeof AppExpensesRoute
  '/inventory': typeof AppInventoryRoute
  '/payments': typeof AppPaymentsRoute
  '/reports': typeof AppReportsRoute
  '/settings': typeof AppSettingsRoute
  '/statements': typeof AppStatementsRoute
  '/vendors': typeof AppVendorsRoute
  '/invoices/new': typeof AppInvoicesNewRoute
  '/purchases/new': typeof AppPurchasesNewRoute
  '/invoices': typeof AppInvoicesIndexRoute
  '/purchases': typeof AppPurchasesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/activity': typeof AppActivityRoute
  '/_app/cashflow': typeof AppCashflowRoute
  '/_app/customers': typeof AppCustomersRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/expenses': typeof AppExpensesRoute
  '/_app/inventory': typeof AppInventoryRoute
  '/_app/payments': typeof AppPaymentsRoute
  '/_app/reports': typeof AppReportsRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/statements': typeof AppStatementsRoute
  '/_app/vendors': typeof AppVendorsRoute
  '/_app/invoices/new': typeof AppInvoicesNewRoute
  '/_app/purchases/new': typeof AppPurchasesNewRoute
  '/_app/invoices/': typeof AppInvoicesIndexRoute
  '/_app/purchases/': typeof AppPurchasesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/activity'
    | '/cashflow'
    | '/customers'
    | '/dashboard'
    | '/expenses'
    | '/inventory'
    | '/payments'
    | '/reports'
    | '/settings'
    | '/statements'
    | '/vendors'
    | '/invoices/new'
    | '/purchases/new'
    | '/invoices/'
    | '/purchases/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/activity'
    | '/cashflow'
    | '/customers'
    | '/dashboard'
    | '/expenses'
    | '/inventory'
    | '/payments'
    | '/reports'
    | '/settings'
    | '/statements'
    | '/vendors'
    | '/invoices/new'
    | '/purchases/new'
    | '/invoices'
    | '/purchases'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/_app/activity'
    | '/_app/cashflow'
    | '/_app/customers'
    | '/_app/dashboard'
    | '/_app/expenses'
    | '/_app/inventory'
    | '/_app/payments'
    | '/_app/reports'
    | '/_app/settings'
    | '/_app/statements'
    | '/_app/vendors'
    | '/_app/invoices/new'
    | '/_app/purchases/new'
    | '/_app/invoices/'
    | '/_app/purchases/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/vendors': {
      id: '/_app/vendors'
      path: '/vendors'
      fullPath: '/vendors'
      preLoaderRoute: typeof AppVendorsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/statements': {
      id: '/_app/statements'
      path: '/statements'
      fullPath: '/statements'
      preLoaderRoute: typeof AppStatementsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports': {
      id: '/_app/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/payments': {
      id: '/_app/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof AppPaymentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inventory': {
      id: '/_app/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof AppInventoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/expenses': {
      id: '/_app/expenses'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof AppExpensesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/customers': {
      id: '/_app/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof AppCustomersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/cashflow': {
      id: '/_app/cashflow'
      path: '/cashflow'
      fullPath: '/cashflow'
      preLoaderRoute: typeof AppCashflowRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/activity': {
      id: '/_app/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof AppActivityRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/purchases/': {
      id: '/_app/purchases/'
      path: '/purchases'
      fullPath: '/purchases/'
      preLoaderRoute: typeof AppPurchasesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/invoices/': {
      id: '/_app/invoices/'
      path: '/invoices'
      fullPath: '/invoices/'
      preLoaderRoute: typeof AppInvoicesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/purchases/new': {
      id: '/_app/purchases/new'
      path: '/purchases/new'
      fullPath: '/purchases/new'
      preLoaderRoute: typeof AppPurchasesNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/invoices/new': {
      id: '/_app/invoices/new'
      path: '/invoices/new'
      fullPath: '/invoices/new'
      preLoaderRoute: typeof AppInvoicesNewRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppActivityRoute: typeof AppActivityRoute
  AppCashflowRoute: typeof AppCashflowRoute
  AppCustomersRoute: typeof AppCustomersRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppExpensesRoute: typeof AppExpensesRoute
  AppInventoryRoute: typeof AppInventoryRoute
  AppPaymentsRoute: typeof AppPaymentsRoute
  AppReportsRoute: typeof AppReportsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppStatementsRoute: typeof AppStatementsRoute
  AppVendorsRoute: typeof AppVendorsRoute
  AppInvoicesNewRoute: typeof AppInvoicesNewRoute
  AppPurchasesNewRoute: typeof AppPurchasesNewRoute
  AppInvoicesIndexRoute: typeof AppInvoicesIndexRoute
  AppPurchasesIndexRoute: typeof AppPurchasesIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppActivityRoute: AppActivityRoute,
  AppCashflowRoute: AppCashflowRoute,
  AppCustomersRoute: AppCustomersRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppExpensesRoute: AppExpensesRoute,
  AppInventoryRoute: AppInventoryRoute,
  AppPaymentsRoute: AppPaymentsRoute,
  AppReportsRoute: AppReportsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppStatementsRoute: AppStatementsRoute,
  AppVendorsRoute: AppVendorsRoute,
  AppInvoicesNewRoute: AppInvoicesNewRoute,
  AppPurchasesNewRoute: AppPurchasesNewRoute,
  AppInvoicesIndexRoute: AppInvoicesIndexRoute,
  AppPurchasesIndexRoute: AppPurchasesIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
